### ISSUE TITLE
Occulus is not working.

### ISSUE THREAD

**Issue by Hrafnhild** [Mithion/ArsMagica2#1014]
Greetings,
I am looking forward to this mod!
I installed it to a forge server and my client. I had to change the custom npc config file because of enchantment conflicts but I figured that out on my own and the server quit crashing.
I found a lake of the magic fluid and placed my book. It gave me a compendium. I made an Occulus according to the book and placed it in a house in a nearby village.  When I click on it it tells me 'You cannot comprehend what you see in the occulus.'  
Am I doing something wrong or is this a bug?

**Comment by Mithion** [comment]
You need at least one magic level to view the occulus. You get that first one by picking up the compendium. If you didn't get it, just throw it on the ground and pick it back up. If that doesn't work (for example due to a mod conflict somehow or whatever), you can enter the following command: 
/setmagelevel 1
