### ISSUE TITLE
Dispelling Imbuement Server Kick

### ISSUE THREAD

**Issue by Hellhound732** [Mithion/ArsMagica2#1084]
In the mod pack that I am currently using I finally was able to imbue my armor with tier 4 imbuements, and decided to go for dispelling. I play this on a server and when I put my pants back on after putting dispelling on my leggings, I would constantly get kicked from the server with an "Internal Server Error" message. I can join the server and wait half a second before I get kicked, in that time I have removed the leggings, only to find that they are back on when I come back onto the server.

**Comment by TherminatorX** [comment]
Can you get the FML log from the server at the time of your kicking?

**Comment by Mithion** [comment]
I agree - 
It's very likely related to the SSP crash regarding dispelling, so I have a good idea where to look...but the logs would immensely help narrow it down.

**Comment by Hellhound732** [comment]
I am currently trying to get a server log from the server admin. I am somewhat sure that he will help considering how I am not the only one on the server unable to join because of this same bug. I will post it on the thread if I can get the log.

**Comment by Hellhound732** [comment]
I looked back in the other bug reports that have been reported on this forum and noticed that a cause for this crash was infernal mobs. The server does have infernal mobs, however, it does not crash when I am hit by one, just when I enter the server. It is extremely hard for me to get a server log with the crash due to the fact that I am in a 6 hour time difference with the server owner and he wants to copy the log as I crash but we are in very different zones so this may be very difficult.

**Comment by Nullga** [comment]
Hi, I just wanna follow up regarding the issue since I'm getting the same thing after adding Dispelling to my leggings. I took a server log and also crash-report of when it happens on single mode. While this apperently is not causing the server to crash and the client as well (though it pops up an error message "Internal server error" thingy) however it crashes the client when I try to reproduce the error on single mode. I hope this helps you out.
Server log http://pastebin.com/dT7igxjn
Client log http://pastebin.com/J9hahPiW

**Comment by Mithion** [comment]
Corrected in 1.4.0.009 Dev
