### ISSUE TITLE
Fall Damage and Nature Affinity

### ISSUE THREAD

**Issue by Bluexin** [Mithion/ArsMagica2#1124]
I found something strange lately: the spider-type wall climbing from the Nature Affinity doesn't reset fall damage.
Like if you jump off a cliff, begin climbing, you're fine until either you go "slowly" to the ground or (and that's when it gets really surprising) when you climb all the way to the top once you begin walking again you take all the fall damage... I think that's not the way it was intended to be o_O

Also, when using teleportation skills, fall damage don't reset either... It might make sense for Blink, but for things like the one where you teleport back to a place you marked before (can't remember the name...) it is a bit weird since even when falling you're visually not going down anymore, but the fall damage still stacks...

PS: Sorry if things are a bit tricky to understand, I'm not an English native... I might look into making french localization for your great mod if I find some time ;)

**Comment by Mithion** [comment]
I'd be totally down for a french translation of the mod.  Hopefully you can find some time! :)

**Comment by Mithion** [comment]
Nature affinity now grants a slowfall-like buff called "Leaf on the Wind", which also negates fall damage.  It still has all other perks/drawbacks.

As for the teleports, this makes sense, as walking through a portal (or teleporting) just moves you to another place; it doesn't change the speed you were going when you did.  Thematically it works the way I want it to, so that won't be changed.  Teleportation isn't meant to be a fall-damage saver.  If you want it to be one, you can customize the spell to additionally protect you from the fall.

Closing this as fixed in dev for 1.4.0.009 release.
