### ISSUE TITLE
SMP "randomly" resets compendium progress

### ISSUE THREAD

**Issue by Jomik1** [Mithion/ArsMagica2#1145]
So I've had some weird resets in my compendium when playing on SMP, curious as to where the compendium unlocks are saved when you play on SMP, as both the compendium folders are empty. It's been halting my progress a bit, and I do dislike having staged compendium off, due to not being fluent in Ars Magica, I'd like it to be fed to me gradually :)

**Comment by Mithion** [comment]
Were I still working on the mod, the state of the compendium unlocks would be the first thing I would rewrite.  Perhaps I should hint at this to the new developer :P

There are a couple of things to note regarding how the compendium unlocks currently work:
1.) Compendium unlocks are clientside only - this means they will never exist in a server's instance folder.  You'll want to check your client instances.
2.) If you're moving from computer to computer, your compendium unlocks will not go with you.  This is the largest factor in me wanting to rewrite it.  The current implementation is admittedly rather short sighted.
3.) LAN is just plain weird - if at all possible, don't use it (I recommend setting up a local dedicated server instead).  It seriously breaks the compendium unlocks, in that only the host gets the compendium unlocks file properly.
4.) The folder these should be under is "<your_instance_folder>\compendiumunocks\<your_world_name>.txt"

If you're stuck, and running the latest version, there is a command called "/unlockcompendiumentry <entry_id>" that can unlock specific entries, if it turns out you do need to reset your progress, or if something isn't unlocking properly.  All entry IDs are in the compendium's XML file. For example, to unlock the ritual of purification you would enter:

/unlockcompendiumentry purification

I hope that helps point you in the right direction.

**Comment by Jomik1** [comment]
Ahhh. That's probably the reason then. Yeah. I'm using a LAN SMP. So I guess it's all going on that server. Hmmm. But it also was an issue when I was doing it. And I actually can't see the compendium unlocks on the one hosting the LAN, but I guess it's because the host doesn't have AM2 unlocked yet?
The command implies that I know what I need to unlock :P But yeah, thank you. I suppose I'll need to set up a dedicated server to run this.

- Curious though, you've mentioned "new developer" a few times on these issues. Is he/she anonymous? Was looking to get back into minecraft modding, but well, don't have many ideas for a new project :P

**Comment by Iivaitte** [comment]
Jomik1 I'm working on a mod if you would like to help out admitting the thing I need the most is  textures. I'm far too embarrassed at my texturing abilities to even try. Contact me on minecraftforum to talk more about it.

**Comment by Mithion** [comment]
Any compendium entry's key can be found in the ArcaneCompendium_en_us.xml file inside the jar (or on this github, though it's still outdated).

Yep, there is a new dev.  He's working on a 1.7.10 bugfixing update, then will be tackling the 1.8 update after.  Don't think he's looking for any additional devs ATM though, but can't say for sure.  I don't speak for him in any official sense.  I'll happily speculate though :P
