### ISSUE TITLE
Incompatibility with Thaumic Horizons 

### ISSUE THREAD

**Issue by wrothmonk** [Mithion/ArsMagica2#1167]
I seem to be running into some compatibility issues with Ars Magica and Thaumic Horizons. It launches fine but when I create a world or attempt to go into an existing world it crashes. Unfortunately this doesn't generate a proper crash log for whatever reason. There does however appear to be another sort of error log generated in the minecraft folder that I've never seen before.

I'm certain its due to incompatibilities between the two mods since they both work perfectly on their own and with other mods but when put together it results in a crash.

Logs
Forge latest (two parts because its too big for one pastebin)
Part 1: http://pastebin.com/Xu7BAJmG 
Part 2: http://pastebin.com/FfW044NK

Other error log
hs_err_pid20599.log: http://pastebin.com/8dzWKzJn

**Comment by Mithion** [comment]
There is no crash in the crash reports - the other error log indicates your JVM crashed, which isn't something that AM2 causes.  try updating your java version.

**Comment by Gunner76th** [comment]
I am with Mithion on this one. First off, you need to research the code in the hs_err_pid20599.log file, located in line 4. Find out what that error means, and what steps are needed to resolve it. I would try updating to Java 8, as it is not out, stable, and the preferred version of java when using forge beyond version 1280. 

As to the incompatibility issue, there is no abnormality in your server start log files to indicate any sort of issue. Because forge successfully loaded, and was loading mods, I can 100% promise you that *IF* your world had crashed as a result of a compatibilty issue, or some other mod related issue, a crash report would have been created in the /minecraft/crash-reports folder. 

Also, if you are going to link a server/client console log file, please pot it in its entirety using either Paste.ee or a gist.github.com. Just by looking at the links you posted, I can tell you have trimmed the beginning and end of that log file, and possibly removed lines that while you might have thought were not important, might actually reveal to us some important information. 

Finally, is this a personally created mod pack, or is this a mod pack found on one of the groups like Feed the Beast, Technic, ATLauncher, etc...?

**Comment by wrothmonk** [comment]
1: I am using java 8 update 45
2: I'm certain its a compatibility issue since the crash only occurs when both mods are together. Everything works fine with them separately. I don't know what else to say.
3: I did not trim the log file at all to my knowledge, something must have happened to the file when it was writing it or copy/pasting it.
4: Its a personally created modpack.

**Comment by Gunner76th** [comment]
As to java, I am sorry to inform you but you are not using Java 8. [09:52:25] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_71, running on Mac OS X:x86_64:10.10.3, installed at /Library/Java/JavaVirtualMachines/1.7.0_71.jdk/Contents/Home/jre clearly states which Java is being called when minecraft starts. 

If you do infact have Java 8 installed, you will need to uninstall Java 7, or find out how to force Java 8 to be used. 

As to the incompatibility, unless you can provide an actual crash report from Forge, not from Java, or some other means of producing evidence of this issue (screen captured recording of the event happening), there is nothing here to prove as much. Your console log shows no irregularities, and the log file you provided is because of Java itself having an issue, which is entirely separate from a minecraft mod issue. 

As mithion stated, nothing you have provided shows any problems or issues between Ars Magica and Thaumic Horizons.

**Comment by Alaberti** [comment]
How much memory did you give your pack?

**Comment by Mithion** [comment]
Leaving this open so the discussion can continue - but this isn't AM2's cause.

Please close this when you are done.

**Comment by wrothmonk** [comment]
Just close this. I'm not going to fuck with it since I already spent hours to figure out how to get minecraft to run Java 8 only to find out it isn't. I'll find other mods to use.
