### ISSUE TITLE
Soulbound items disappear when dying in the Nether/End

### ISSUE THREAD

**Issue by EoD** [Mithion/ArsMagica2#1209]
AM2 1.4.0.008

If you die in survival with soulbound items in your inventory, they are gone after respawning in the overworld. It is important that you respawn in a different world than you died in.

I was able to recover **all** items after my death except for those which were soulbound. Those just disappeared from the world. I could reproduce the problem several times.

I will try this in other dimensions (Galacticraft / Extra Utilities dimensions), once I got access to it.

This might be a duplicate of  #1144 and #1096 . Either way #1096 should be renamed in order to reflect the bug.

**Comment by jjtParadox** [comment]
This issue has been fixed and should be closed.

**Comment by EoD** [comment]
@DoomFruit says that #1231 "possibly" fixes the issue. I will test and close it, once I got an updated version of the mod.

**Comment by DoomFruit** [comment]
I said "possibly" because I haven't tried every single possible combination of mod dimension and exit method. What I did try was end + dragon's portal, end + jumping off the edge, nether portal transits and nether + swimming in lava - repeatedly doing all cases did not cause me to lose any soulbound items upon respawn. I haven't tried other mod dimensions yet simply because I don't have any other mods in my dev environment.

**Comment by jjtParadox** [comment]
Just tested with Extra Utilities, and I can confirm soulbound items persist even when dying in both the EU dimensions.

As long as mods use proper dimension transfers that fire events (which minecraftforge mods should), DoomFruit's fix should work just fine.

**Comment by EoD** [comment]
I can confirm that the jar Doom provided me with, fixes the issue.

**Comment by TerdyTheTerd** [comment]
I know this is beyond your scope of responsibilities, but this still doesn't work for Kcauldron servers, I don't expect anyone here to care much since hardly any mod authors support Kcauldron in the first place, but if you feel nice and want to look into it I'm sure many people would appreciate it. Testing both versions .008 and .009 on forge work fine, but both of them don't work for KCauldron using the same forge build numbers

**Comment by Mithion** [comment]
Cauldron/Bukkit is as a rule not supported.  If they want to make a framework that works cross platform, then they need to call all relevant events.  If they did, then all applied fixes would also work in that scenario as they do in Forge.

**Comment by Razorskills** [comment]
Lol, il leave this here.. https://gitlab.prok.pw/KCauldron/KCauldron/issues/196

**Comment by Mithion** [comment]
and that accomplishes...what?
So they won't fix their broken system.  That's fine...like I said, I don't support Cauldron, I support Forge, where this works fine.  If they want to fix their system to properly emulate forge it'll work.

**Comment by jjtParadox** [comment]
@Bogdan-G @TerdyTheTerd I did some digging and confirmed this is a direct issue with KCaudron, which I detailed as a comment over [here](https://gitlab.prok.pw/KCauldron/KCauldron/issues/196).

**Comment by TerdyTheTerd** [comment]
@jjtParadox thank you for looking into this, currently we are tracking it on a fork of KCauldron [here](https://github.com/TCPR/KCauldron/issues/39#issuecomment-176930572)
