### ISSUE TITLE
[v1.4.0.008] Can't Drink Mana Potions at Full Mana or Mana Martinis at Full Hunger; Can't Cast Dispel without Active Effect

### ISSUE THREAD

**Issue by Eunomiac** [Mithion/ArsMagica2#1220]
(Apologies if these issues have already been addressed, they were a bit harder to search for than my last two.  Fear not, this is my last issue post! :) )

The following may or may not be intended behavior, I'm not sure.  But, as they're all somewhat related, I thought I'd combine them all into one issue:

* I can't drink a Mana Potion (of any kind) if I am at full Mana.  This would make sense if Mana Potions restored a fixed amount of mana, rather than providing a duration-based regeneration effect that you often want to quaff in preparation for a fight (before you've spent any mana).
* I can't cast a Self + Dispel + Shield spell unless I'm afflicted with something for the Dispel component to get rid of.  I intended this to be my general-purpose Shield spell, just with the added perk of wiping away any negative status effects first.  Should the entire spell fail because the Dispel component has nothing to do?
* I can't drink a Mana Martini if I'm at full Hunger.  This is especially egregious, as it runs contrary to my mother's wise counsel to only drink alcohol on a full stomach---especially magical alcohol.

**Comment by jjtParadox** [comment]
@Mithion, any input on this?

**Comment by Mithion** [comment]
My original intentions were to make it so you couldn't accidentally waste magical food items.  If it's preferred to always be able to use them, that's fine by me.

As for the dispel + shield, that *should* work, as each component is applied individually in a spell stage and shouldn't affect the application of the other ones (unless explicitly coded to do so.  Dispel is not.
The only thing I can think of is that Dispel is throwing an exception, which would stop the spell from continuing to execute - check the error log when you try that spell.

**Comment by jjtParadox** [comment]
Just did some testing, and what's strange is when in creative mode the shield effect appears after about a second after the dispel, but in survival the shield effect never appears.

After some digging, I've found the bug here is a desync issue, as the dispel effect only dispels the shield on the client, not on the server. You can see this by casting Dispel + Shield, logging off, then logging back on. The shield effect is then present.

I'll make a fix so that dispel only runs on the server side, then updates the client.

**Comment by Mithion** [comment]
Corrected by #1268.
