### ISSUE TITLE
Etherium vs (raw) Essence

### ISSUE THREAD

**Issue by EoD** [Mithion/ArsMagica2#1265]
I just figured out by chance that in the german translation (de_DE.lang) the "raw" essence is still called "Essenz" (=essence) and not "Etherium", which would be a valid german name.

Is this intentional?

**Comment by Mithion** [comment]
The German translation is old, and was done before Essence was renamed to Etherium.  It was done because I was calling too many things "Essence".

It's a word I made up (as far as I know) so it could probably be treated like a proper name (which wouldn't be translated).  I'm not at all familiar with the German language so I don't know if that would work.

**Comment by EoD** [comment]
This has already been changed (Essence->Ätherium) in the german translation file before the open source commit. I created a new pull request to restore those language files.
