### ISSUE TITLE
Inconsistent behaviour of Grow componenent

### ISSUE THREAD

**Issue by EoD** [Mithion/ArsMagica2#1291]
The grow component behaves incosistent with AoE (without gravity) and Projectile/Beam. I am currently trying to generalise its behaviour, but I am not sure about some bits of the code.
Namely the latest commit EoD/ArsMagica2@22f8012f0fced78aff08d2f124194e8b473030b3 in https://github.com/EoD/ArsMagica2/commits/rewrite-grow-spell-component

@Mithion could we have a chat about this?

**Comment by Mithion** [comment]
The check is needed, as if farmland is targeted for growing it should actually target the IGrowable that's been planted on the farmland and not the farm land itself.

The goal is not to make grow the be-all-and-end-all of smart spells - the point is to require some forethought and planning by the player in order to make the spell target what they want it to.

As a general rule, components should not really target anything.  They should apply their effect at the given coordinates and that's it.  In some rare cases this might need to be altered a little bit (such as in this case or in the component that destroys leaves...don't remember what it's called but it has a built in AoE).

For this check though, one would generally need target non-solid blocks in the spell so that it does what is intended, and actually grows the crops.  However, because different growing mechanics work in slightly different ways, certain special circumstances were deemed necessary.

So yes, the grow component behaves inconsistently if you don't build your spell right.  That's intended.  Grow should not be made into a "smart" component that auto-targets.  That's what shapes and modifiers are for, and is part of the challenge.

**Comment by EoD** [comment]
When I removed the farmland check I couldn't notice any difference between my Grow+AoE(+/-Grav) and Grow+Projectile spells. Can you give me an example where it is needed?

**Comment by Mithion** [comment]
In the case of AoE, the AoE will expand and target the plant directly which will do what you'd expect.

Projectile + grow without target non-solid blocks will pass right through the crops and hit the farmland below it.  This causes the grow to do nothing. The only thing I can think of at the moment that would cause this to still work is the Forge BonemealEvent that is being called.  If that is in fact the case, then you are correct in that the code is not needed.

The remaining thing to try is to shoot projectile+grow at the side of a farmland block with crops on top of it.  I would think that if the caster ever comes back, it would be a good idea to make something like that work, as there is no modifier that causes a spell to search upwards.  This could be solved by leaving the statement in, or adding the aforementioned modifier.

**Comment by EoD** [comment]
I tried to reproduce the growing from scratch, but you were totally right. It does not work without AoE. What is your opinion on changing 

```
		if (block == Blocks.farmland){
			blocky++;
			block = world.getBlock(blockx, blocky, blockz);
		}
```

to 
```
		if (!(block instanceof iGrowable) && 
				!world.getBlock(blockx, blocky + 1, blockz).isNormalCube() && 
				!world.getBlock(blockx, blocky + 1, blockz).isAir(null, 0, 0, 0)){
			blocky++;
			block = world.getBlock(blockx, blocky, blockz);
		}
```

Basically checking if the block is not ``IGrowable`` and the block above is neither solid nor air? This allows to use the Grow+Projectile on podzol and sand and let flowers grow there, too.

Another option would be to check for ``block instanceof BlockFarmland``.

**Comment by Mithion** [comment]
Works for me.  Allows Grow to search upwards one block when applying the effect, but no more.

**Comment by EoD** [comment]
I had to remove the ``!(block instanceof iGrowable)``  as ``Grass`` is of type ``IGrowable`` and sapling on top of the grass won't grow with the above conditions. I couldn't think of a scenario where someone wants to grow an ``iGrowable`` when there is something on top of it.

I also can't check for ``block.isNormalCube()`` because ``Farmland`` is not ``.isNormalCube()`` and this is our standard case.

Instead I added the condition that the spell has to come from above (``blockFace==0``). For the player the seed only grows when he actually hits and therefore hitting the block below from above.

This is the solution 82305f9a999c6bce831448ec425d40f682e7d1ab . If you are ok with the final solution, my pull request is ready to be merged.

**Comment by Mithion** [comment]
Why not just have grow always check the coordinates passed in, and if it doesn't grow anything it searches the block above for a growable?

**Comment by EoD** [comment]
I see only a slight issue: If you have a tree sapling on top of a grass block, the projectile will hit the grass block and go into  ``if (block instanceof IGrowable){`` and successfully pass ``canFertilize()`` and ``shouldFertilize()`` and call ``fertilize()``. From this stage on, we cannot distinguish if the growth spell has been executed or if it hasn't as ``fertilize()`` on ``BlockGrass`` will also grow grass/flowers on surrounding ``BlockGrass``. Effectively ignoring the sapling at all.

The solution I chose has the drawback that there won't be a bonemeal-like effect which produces flowers and other grass if the spell comes from the top and the top is occupied by a sapling. On the other hand it will have a bonemeal like effect if it is used from the side of the grass block.


If you want to run (parts of) the method twice, do you want to call the ``BonemealEvent`` twice? As far as I understood the current logic is to have only one ``BonemealEvent``, hence the farmblock check above. I am not familiar with the ``PlayerEvent`` class of MC, so I don't know if that would have any implications.

**Comment by Mithion** [comment]
Ideally situations like these should be detected and handled but there really is no way to know what blocks need to be searched up for (due to other mods).

That's why it might just be better to apply at the given coordinates only and let custom spell grammar allow the player to control where the spell looks.

I'm still leaning towards a modifier that will cause spells to look up instead of down, and let the player control how it targets.

**Comment by EoD** [comment]
If we want the player to fully control the spells we should remove the farmland/blockface check and force the player to use "target non-solid blocks" for crop-growing.

What disadvantage do you see in 82305f9a999c6bce831448ec425d40f682e7d1ab? It is just an extended version of the ``block == Blocks.farmland``. This could at least serve as an intermediate solution.
```
		if (blockFace == 0
				&& !world.getBlock(blockx, blocky + 1, blockz).isNormalCube()
				&& !world.getBlock(blockx, blocky + 1, blockz).isAir(null, 0, 0, 0)){
			blocky++;
			block = world.getBlock(blockx, blocky, blockz);
		}
```

**Comment by Mithion** [comment]
As for what's wrong with 82305f9:

It isn't a generic solution and won't solve the future issue of caster blocks targeting the side of farmland.  Plus it isn't intuitive and for all we know the player may not want to target one block above if they shoot the block from the top.

That's why grow should just apply directly to the coordinates passed in; from there it's up to the player to use spell grammar to target the way they want it to.  It gives the most flexibility (and the gravity/antigravity modifiers don't need to be expensive either).  I agree with removing the check altogether and making spell grammar be the determining factor in what's targeted.

**Comment by EoD** [comment]
"Removing" it is then.
