### ISSUE TITLE
Spellbook Opens on Certain Spells

### ISSUE THREAD

**Issue by malignantMystic** [Mithion/ArsMagica2#1302]
Mentioned this in #1287 a week or so ago.

Essentially, if you attempt to put a Channel: Telekinesis or Channel: Attract (or combinations of the two components) spell into the spellbook, they cannot be used properly due to how the spellbook functions. To open the spellbook, you press Shift and right-click, which opens the GUI. This works regardless of whether a spell is selected or not. To use Attract, you need only initially hold right-click to channel the spell. However, to shift the position of the spell (aka move the entity), you hold Shift + right-click, and scroll with the mouse wheel. Shift-scrolling is also how you switch spells in the book (aside from the Z/X keys). When you do that, the game both attempts to move the channel's position and switch to the next spell, which opens the book.

Last tested in .008, no additional mods, updated Forge version, etc. etc.

**Comment by Mithion** [comment]
Thanks @jawdylady for splitting this into a separate issue.

I believe the best fix would be to remove the "Shift + Rclick" method of opening GUIs altogether and have a new configurable hotkey designed to open these GUIs, as was suggested in #1287.

This would affect all guis that open this way, including the rune bag, the essence bag, the spell book, and anything else I forgot.  It wouldn't affect the special functionality of the crystal wrench.

I'm open to thoughts/suggestions about this though, as always.

**Comment by jawdylawdy** [comment]
Maybe giving the spellbook a sort of "equipment slot" would work? Have a single extended slot on the hotbar that, when scrolled to, will have the existing functionality of Shift-scroll to rotate between spells, while also not opening the book itself on use. Instead, you would take the book out of its equipment slot and switch spells that way. Not unlike 1.9's off-hand slot. I've seen something similar done with Witchery's vampire powers (e.g. an extended part of the hotbar), and extra slots aren't exactly new (Mine + Blade Battlegear). That is, of course, a rather difficult task to accomplish, but it was the first thing that popped into my head.

Branching off of that, maybe instead of having an extended slot on the hotbar, a keybind to switch from your active item to your current spellbook within its equipment slot. That way you can snap from a sword to a healing spell if things get tricky.

**Comment by Mithion** [comment]
The problem with that implementation is to switch a spell you need to open your inventory, switch out the spell book to somewhere else that lets you edit it, make your changes, close the spell book, open your inventory, switch the spell book back, then close your inventory...a very tedious process.  

Right now the spell book works consistently with the way the rest of the items in the game are used.  
A system like that would work better if spell books weren't item-based.

The spell book kind of already is an extension of the slots as it lets you put a whole bunch of spells into one slot, and has a separate UI element for managing it.

I could see something like 1-4 configurable "quick cast" keys that correspond to additional equipment slots where you can put individual spells in. Hitting the button casts the spell instantly, but that's tangent to the issue at hand, and would be a separate suggestion/post/...thing.

It also doesn't keep things consistent with the way you open the UI on rune bags, essence bags and the like.  While not necessarily mandatory, it would definitely keep things more simple and contribute towards making the mod a little easier to use.

**Comment by jawdylawdy** [comment]
There are a few steps that can be cut out of the first part; when the book is in the equipment slot, why not just have a keybind to open it up directly? It's definitely not consistent, but it does cut out quite a lot of arduous tasks to switch out a simple spell.

Right now, a keybind to open the spellbook or other micro-inventories sounds like the best option.

**Comment by Mithion** [comment]
Personally I always liked that it took a little bit to switch a spell.  It reinforces the "wizards prepare in advance" mentality.  I don't want it to be to the point of tedious though.  That's not good.

As far as the keybind, I think so too.  That alone would speed up the process.

**Comment by DoomFruit** [comment]
How about a different approach: while you're holding down the use key with a spellbook or spell active, the normal interaction mode of the scroll wheel (hotbar selection) is disabled and over-ridden to instead send "increase/decrease" commands to the spell. That way, there's no need to hold crouch and scroll to change the distance, nor is there any conflict with the crouch-use key combination to open the spellbook.

**Comment by jawdylawdy** [comment]
Ahh, sweet necromancy... I forgot about this issue!

I like Doom's idea. Having the spellbook circumvent the scroll wheel functionality would both solve the telekinesis/attract thing and (kind of) slow down how much you can swap between magic and melee.

**Comment by jjtParadox** [comment]
I just took a gander at the code for managing the scroll wheel, and it appears there's already some implementation of DoomFruit's idea. If a spell is being held active, and that spell is in a spell book, pressing shift and scrolling the scroll wheel will adjust the spell, not the book.
However, DoomFruit's idea seems much simpler since holding sneak is not required. Later I can try to fully implement his idea and hopefully close this.

**Comment by jjtParadox** [comment]
Oh looks like I misinterpreted the code, as holding sneak is not required at all!
Instead, I believe the compendium entry for telekinesis needs to be updated to say 
> Rolling the mouse wheel while casting/sustaining the spell can change the distance of the point closer or farther away from you.

instead of 
> Sneaking and rolling your mouse wheel can change the distance of the point closer or farther away from you.
