### ISSUE TITLE
spell casting modes

### ISSUE THREAD

**Issue by Webber88** [Mithion/ArsMagica2#1313]
the modes thing is bugged it doesnt switch (i even rebound the key to something not used and it still didnt work)

**Comment by EoD** [comment]
As far as I Know, there is no spell casting mode as of AM 1.4. Would have been a good idea to change Ars Magica to a version 2.0, just to reflect all those game mechanic changes :)

**Comment by Mithion** [comment]
Probably, but too late for that now.

**Comment by EoD** [comment]
Never to late to increase a version number ;-)

We could re-formulate the bug and put it "Spell casting mode Keybinding does nothing" and fix it by removing the keybind?

**Comment by jawdylawdy** [comment]
As far as I know, the keybind still does something; if a spell has multiple separate targeting shapes, it cycles between those, changing how the spell functions.

**Comment by Mithion** [comment]
True, very true.
I was planning to increase to 2.0 if/when the update to 1.8/1.9/3.14159 happens.  Figure that's a nice point to roll it over.

**Comment by Webber88** [comment]
so is there a link i can get for 2.0 (i think im currently running 1.4 or something around there) and is the nxt update gonna be for 1.8/1.9?

**Comment by EoD** [comment]
So it is supposed to change between the 3 targeting shapes, but it doesn't do anything? Is there a GUI indicator to show if you successfully changed? Personally, I always thought the keybind does nothing.

@Webber88 currently there is only a 1.7.10 release planned.

**Comment by Mithion** [comment]
Casting modes were removed in a much older version...I want to say 1.2.  The keybind now handles changing between spell shape groups.  

The keybind won't do anything if your spell only has one shape group, because there are no other shape groups to change to.

If you're looking for functionality like casting modes to change the power level of spells, it no longer exists in that form.  The way to do it is to create multiple shape groups of varying power when you make your spell, and then you can cycle between them.

**Comment by jjtParadox** [comment]
This can probably be closed, since this is now done by a newer feature of AM2.
