### ISSUE TITLE
Level 40 Infusion Client Kick

### ISSUE THREAD

**Issue by tyler2k15** [Mithion/ArsMagica2#1333]
Hello

On my Hubris server, I had a player try to do a level 40 infusion. After the server restarted, the player was unable to connect with the following in console.

https://gist.githubusercontent.com/tyler2k15/712001fcf42b8ecd7bd6/raw/b437ce13f2a06090ed0a687f13736f379b97144a/ClientCrashThaumicTinkerer.txt

I was able to remove the armor from their inventory and they could then connect. After them connecting I put the armor back in their inventory but it was invisible to them so they relogged and when they logged back in the armor had vanished

**Comment by Zieg777** [comment]
From reading that, I'm guessing he put dispelling on legs, which conflicted with some of his kami gear's enchants?

**Comment by InfinityRaider** [comment]
According to the code, a private field with index 35 in the declared fields array is requested, which is a boolean, however some mod must have used ASM to add/change the Potion class so it's returning the wrong field (not a boolean).
Preferred method would be to use an array of fieldNames (obfuscated and deobfuscated) to retrieve the field.

**Comment by Mithion** [comment]
You're completely correct in that case, as far as the better method.  The implemented method was only intended to be a temporary test, but it appears I forgot to clean it up once I got it working with the rest of the functionality.

**Comment by InfinityRaider** [comment]
It's not your fault, just careless coremodding

**Comment by CraigParton** [comment]
The obfuscated name for isBadEffect is field_76418_K. After looking at Potion.class I can't understand why they made isBadEffect() a client-only method.

This does the reflection in method so it's a little clunky, but it works and fails gracefully, ignoring that effect, no matter what goes wrong or how the Potion class is changed. 
http://pastebin.com/p1VdKNWb

You could also use the ReflectionHelper library and just specify the obfuscated field name instead of the index number. Only thing is the getPrivateField() method auto casts to the object type its being assigned to, so unless you assign it to an Object and test with instanceof yourself there's still a small potential for failure.. assuming the type of field_76418_K gets changed.

**Comment by jjtParadox** [comment]
I believe this has been fixed by #1322, as now AM2 uses obf/deobf pairs for bytecode transformations.

**Comment by jjtParadox** [comment]
@kolatra this issue can probably be closed. @tyler2k15 if you're still having these problems with the newest version of Ars Magica (v009), feel free to create a new issue or comment on this one.
