### ISSUE TITLE
Crash Log

### ISSUE THREAD

**Issue by PrinceRenais** [Mithion/ArsMagica2#1366]
My father put together a server, and I've been helping him put mods in, but something is wrong on his client. Everything is fine on the other 3 players' windows computers, but something about Ars Magica 2 on his Linux version crashes it. I'm assuming this error is related to Ars Magica based on the fact removing the mod fixes it, but after having read the dump, I don't really see where in the code it causes a problem. 

I love the mod, and as a temporary fix he's willing to just go play by himself without it, but it'd be great if we could fix our problem somehow.

http://pastebin.com/jGSSJiw7

**Comment by Mithion** [comment]
This looks like a conflict with optifine - easily resolvable though!

If you have optifine in a subfolder, it will not work.  It needs to be in the same folder as AM2.  You also cannot have a file named "optifine.disabled" or some such other format to exclude it - AM2 will currently incorrectly detect it as an active mod and will alter it's bytecode to work with Optifine (but since it isn't there it won't work).

Make either of those changes as needed and you should be good to go.

**Comment by PrinceRenais** [comment]
Thanks for the quick response! That fixed it! We're using the MultiMC launcher, and while I personally remove disabled mods from the folder on my machine via the usual file explorer, he disables them using the launcher such that, as you suspected, the file was still there. Moving it to the trash bin fixed his game!

**Comment by Mithion** [comment]
Cool.  Glad to hear it worked for you.

Closing this issue as resolved.
