### ISSUE TITLE
Levels reset when I leave the end

### ISSUE THREAD

**Issue by ThatOneTraitor** [Mithion/ArsMagica2#1371]
as the title says, my levels reset when i leave the end, this was apparently fixed in 1.2 but is still happening in version 1.4.0.008

**Comment by DrasticDemise** [comment]
This should have been fixed on the latest build. Are you running the download from the Forum or did you build your jar from here?

The issue from the past is #1156 which confirmed that this should be fixed.

**Comment by ThatOneTraitor** [comment]
i'm using the latest build on curse

**Comment by jjtParadox** [comment]
This has been fixed in dev and will be officially available the next update (1.4.0.009).

If you want to get a dev copy before the update comes out, download this repository and run "graldew build" in a command window, then grab the final .jar from build/libs. Some of the other issues opened recently have more information on how to do that.

**Comment by ThatOneTraitor** [comment]
Thanks a Ton :D
