### ISSUE TITLE
Boss Minions

### ISSUE THREAD

**Issue by jeg623** [Mithion/ArsMagica2#1425]
Can you make so we can make bosses (such as the wither) minions? I remember this in 1.6.2 it just spawned infinite amounts of them. It lagged the game so much lol.

**Comment by malignantMystic** [comment]
You intentionally can't make boss minions. Filling up a soul vial would take like a billion years, I don't even want to think of that. I can think of adding more "secret" summons to the game (such as the Hell Cow and the Battle Chicken) which emulate bosses, but maybe not actual bosses. Like a mini ender dragon or a widdle widder.

**Comment by jeg623** [comment]
Yeah but there are those who would want this. Besides, because of how powerful bosses are , I would like to think it's balanced.

**Comment by Mithion** [comment]
Boss minions are intentionally not summons.

**Comment by jeg623** [comment]
well that was closed quickly.

**Comment by jjtParadox** [comment]
Simply put, it's a "feature" that is not wanted in AM2 due to balance and exploit issues, especially in endgame situations.

**Comment by jeg623** [comment]
I understand. Could you at the very least put the option in the config file?

**Comment by jjtParadox** [comment]
The possibility of exploitation (and bugs, considering some of the "interesting" properties of many bosses) is too great. If you wanted to compile your own version of ArsMagica with a config file, go right ahead. We just can't support something that could cause many many headaches and painful days.

**Comment by jeg623** [comment]
OK, that is a good explanation. Maybe just make the wither a minion and ender dragon a minion and restrict it to creative.

**Comment by jeg623** [comment]
And if it's to buggy, don't bother.

**Comment by Mithion** [comment]
So the problem with boss monsters is that they don't typically use the "new" AI in Minecraft, which allows a behaviour-driven approach to tasks.  This AI is required for the summons code to work.

Because of this, most bosses, while technically can be "summoned", *can't* have their AI overridden and would just stand there like idiots at best, attack you as hostile as mid, and flat out crash the game at worst.

The summon code needs to be generic to be able to handle the greatest number of mod-added minions, and special cases such as this, including the config options and all, simply aren't worth the effort, as they would create a lot of confusion as well as additional cluttering bug reports.  Neither of those are things we want :)

Sorry for not explaining fully earlier, was pressed for time and was just trying to keep the queue clean.

Basically, this simply won't happen in any form - with or without a config option.  It's just not feasible and we really have other things to work on that take precedence.

**Comment by jeg623** [comment]
*sigh* fine. Maybe when I learn to code I'll make add-on and maintain it myself I guess. Good luck with further development.

**Comment by Mithion** [comment]
Well, I tried to explain it to you, but if you want to be all angsty about it, then we're done here.
