### ISSUE TITLE
Arcane Spellbook + Random Things White stone = Deleted Spellbook

### ISSUE THREAD

**Issue by plazia** [Mithion/ArsMagica2#1436]
When you get the Arcane Spellbook it has the default Soulbound I enchant on it. Not the Ender IO one the AM2 one. Fair enough.

If you have a Random things White Stone (charged) in your inventory it saves you from death. It does. As soon as you are about to die it tops up your health and gives you some buffs. 

Trouble is ... Someone should tell the AM2 Soulbound enchant. It immediately deletes the Arcane Spellbook and from my testing most other items enchanted with AM2 Soulbound I from inventory.

Steps required to duplicate. Install random things and AM2 together. Cheat in or use your favorite NEI inventory mod to give yourself a charged white stone. Cheat in an arcane spellbook with soulbound I. Allow yourself to ... die sort of. You wont - the stone will save you but not the book.

**Comment by jjtParadox** [comment]
Appears to be a bug caused by AM2 storing soulbound items [here](https://github.com/Mithion/ArsMagica2/blob/master/src/main/java/am2/AMEventHandler.java#L159) before RandomThings cancels the death event. Suggested fix would be to modify [this](https://github.com/Mithion/ArsMagica2/blob/master/src/main/java/am2/PlayerTracker.java#L196) section of code to instead receive all entity death events with `@SubscribeEvent(priority = EventPriority.LOW)`, check for if the entity is a player, then do as already written in that method (just make sure to update the bytecode transformers, too).

I'd do it myself but things are rather busy for me right now. I'll poke IRC and ask if anyone wants to help out with this.

**Comment by Mithion** [comment]
The death event was recently moved to high priority to fix a duplication issue (or some other nonfunction, I forget the specifics) with the gravestones mod though, keep that in mind.

Changing it to low priority could undo that fix.

**Comment by jjtParadox** [comment]
I mean to suggest adding a 2nd death handler specifically for "confirmed" deaths, at a lower priority. The chrono anchor should certainly remain at a higher priority.

**Comment by Kolatra** [comment]
What does the Random Things white stone do? We could easily cancel the event before our onPlayerDeath is called, thus avoiding the "storage" of soulbound items.

**Comment by jjtParadox** [comment]
Random Things does a normal priority entity death subscription, which means the event bus always runs our code runs before RandomThings's code runs.
