### ISSUE TITLE
Error when joining HUB

### ISSUE THREAD

**Issue by Zilacon** [Mithion/ArsMagica2#1460]
Hello. So i added AM2 to my new modpack because so many people requested it. And my network is on a 1.7.10 bungeecord network. Whenever anyone with AM2 joins the hub they get this error message.

http://i.imgur.com/CmybBBG.png

The developer of the server software i am using Minetick found and tracked down the issue to AM2 his explanation of this issue can be found here:

https://github.com/Poweruser/MinetickMod/issues/23

Any fix for this would be great!

**Comment by Poweruser** [comment]
Hi. Steps to reproduce:

1. start any non-mod 1.7.10 server (craftbukkit/paper-/spigot/minetickmod/...)          
2. start the client with this mod and join         
3. add an effect to the player by drinking/throwing a potion, activating a beacon, or by command.              
4. watch getting disconnected

**Comment by jjtParadox** [comment]
Hmm I may have gotten something confused, are you attempting to connect to a server without the server having Ars Magica installed? I'm not entirely familiar with this, but I believe this error is because Ars Magica makes ASM transformations to potions to allow for more complicated status effects, thus more interesting spells. AM2 also assumes every server it connects to has Ars Magica installed, as it cannot disable and enable certain components on-the-fly due to their complexity.

It may be possible to fix, but this situation is rather unique, and developing handlers for every edge case that comes up is generally discouraged, as it's not easily maintainable.

Can you possibly offer more information as to how your "server network" works? The more information the better.

**Comment by Zilacon** [comment]
Bungeecord -> MinetickMod (Vanilla Server) -> Modded Servers (Thermos)
The hub acts as the server between all of the servers on the network so it is vanilla so that it cannot conflict with any modpacks and all packs can join it. Up to this point I have had no issues joining the HUB with any modpack including RR3, Tekkit Legends, Infinity, Agrarian Skies 2, Sky Factory 2, etc. But none of these had AM2.

When a modded server crashes all players are sent to the HUB to wait until the server restarts and comes back online.

The HUB is also responsible for being the "default" server on the network. Meaning all connections go through it and its the main server on port 25565 or when you use the default domain to connect to the network.

When your in the hub you can select which server you want to join by jumping into a portal or doing /server name. So for example the modpack in question is AA so to join AA you would do /server AA and it would send you to that server if you have the correct mods. If not it tells you the mod conflicts and denies you from joining without ever getting the dirt screen. It just gives you a red error message in chat explaining why you cant join.

**Comment by jjtParadox** [comment]
Thanks for the clarification! I tracked down where the error was originating from, and unfortunately I was correct about the ASM transformations to potions (Hey @DoomFruit, do you know if the ASM transformations for the entity effect packets could be easily modified to catch errors that may happen?)

It's likely not easy to fix, so this kind of error may not be possible to work around on our end (we generally don't support servers outside of Forge's server) :disappointed:

However, if @Poweruser is able to readily get a list of mods the client has, it may be possible to account for AM2 and send the changed entity effect packet instead of the vanilla packet (or just not send the packet at all).

I'll keep on looking into the ASM transformations of the entity packets, but it's still rather complex and just about as hacky as a mod can be (ASM modifies the _bytecode instructions_ of compiled and loaded java classes, which is about as close to assembly as Java can get). I'll let you know if I find anything.

**Comment by Zilacon** [comment]
Is there going to be a fixed version for 1.7.10? I would like to update my modpack to fix this bug.

**Comment by jjtParadox** [comment]
The fixes have been merged in, so you should be able to download and compile your own version that includes the fixes. Check the project readme or #ArsMagica IRC for help doing that (we do idle in that channel and see all messages sent, but sometimes it'll take us a while to get back to our computer to see the message. Don't close your IRC client or we won't be able to respond!)
