### ISSUE TITLE
[Suggestion] Burnout

### ISSUE THREAD

**Issue by SneakTrap** [Mithion/ArsMagica2#1545]
It would be good if it were possible to turn the burnout off. It makes it almost impossible to use spells in a usefull way, since you have to wait for it to cool down before you can use spells again.

**Comment by malignantMystic** [comment]
Make spells that are less strenuous or at your level. Burnout is there for balance.

**Comment by SneakTrap** [comment]
But you already have mana for that purpose. I'm not saying to remove it, only to make an option to turn it off in the config. Because in my opinion, the way it works now, you just can't really rely on your spells. Even a simple projectile+magic damage is to pricy to efficiently use in combat. Some may be other opinion, but for those who think so too, it would be nice if you could turn it off.

**Comment by malignantMystic** [comment]
I mean nerfing burnout I can get behind. I don't know how it works at this exact moment, but this seems balanced to me:

Burnout = .5(Initial Cost of Spell) + (Current Burnout)
Post-Burnout Cost = Initial Cost + .5(Burnout)

In other words, let's say you have a spell that costs 200 mana. Casting that will give you 100 burnout. Casting it a second time will cost you 250 mana, and raise your burnout to 200.

Alternatively, Burnout could be a stat on spells and tweaked a little. Instead of burnout affecting you, the player, there is a burnout on the spell — a cooldown of sorts — to encourage variety in your casting.

**Comment by Mithion** [comment]
That was actually the original design of burnout, however having a stat on an item that is constantly updated causes the flickering item glitch, where you basically re-equip it every half second or so.  It's really annoying.

What about mana potions though?  They're actually quite a hard counter to burnout, and there are also talents for faster mana regen and lower burnout accumulation - instead of changing the base burnout, which I personally believe is in a good place, why not try those items and tweak them to be more powerful?  With burnout being as it is, it's an incentive to get them.

The other option too could be a potion you can make that causes significantly lower burnout reduction for x minutes - the strength could be directly tied to the burnout potion's level, and could then have a material cost.

The point of burnout originally is that magic isn't meant to be a be-all-and-end-all.  It's meant to be an effort to get it and to grow in power until you can overcome it (which you completely can).  I believe giving tools to manage it as you go is a much better solution than nerfing it at the base level.

**Comment by malignantMystic** [comment]
Is it possible for burnout to check a list of "stale" spells per player? Like, when you use a spell, it puts it at the top of a list of maybe 10 spells used in the last X seconds, and burns out based on that. The higher the spell is on the list (the more recently it was cast), the more burnout it will incur and the more it will cost. In this way, you don't get that annoying flickering item thing, and burnout can remain more or less the same while being slightly less of a monumental obstacle to work around.

**Comment by Mithion** [comment]
Anything's possible!

It would have to be component based, so the most recent (I would say 15-20) components used, but something like that could be added to EntityProperties and only checked if the isCritical property is set (meaning it's a player character and not an NPC) - less CPU and network overhead that way.

I personally like the idea of the potion more (as MC is typically about collecting resources and such, so it seems more in line with the rest of the game) - however I'm open to ideas, and I don't really play it much anymore.  Just thought I would throw my 2c in because this system is something that I really like :)

**Comment by malignantMystic** [comment]
I think a happy medium could be found! I also like mana potions (preparedness is the sign of any good mage), though I do have to agree that burnout can cripple how useful magic can be.

Another option could be for burnout to scale with the player's level along with the cost of the spell. Not sure how well that would blow over, but I like the idea of progressive difficulty (to a point).

**Comment by Mithion** [comment]
Another idea would be to make a modifier that reduces burnout - takes up a spot in the spell though, so some of the really powerful ones would need to be reworked.  Say each one reduces burnout by roughly 18%, so if you want to put the space in, you'd need to make your spell take up 3 more parts.

**Comment by SneakTrap** [comment]
I still think that it would be a good idea to make a config option for turning burnout off, because some (including me) may want to use magic as a primary weapon and tool, instead of sword and pickaxe. Those who like it the way it is now could just ignore it, while everyone else could turn it off.

**Comment by SneakTrap** [comment]
Alright, I did some testing. My results are:
At level 20 you have 2035 mana. A simple Projectile + Magic Damage costs 100 mana. Without burnout, you should be able to fire around 20 times before you run out of mana. With a damage multiplier of 1.5, one hit deals 9 damage or 4.5 hearts. So fiering 20 times would deal around 180 damage. Divided by 20 (the average health of a hostile mob), you could kill 9 enemies. With burnout however, you can fire 13 times before running out of mana. The total damage you dealt with that amount is 117. Divided by 20 again, you could kill 5 enemies and bring one more close to death.
Considering that this is a very basic spell, that doesn't even use much mana, you couldn't really use more complex spells efficiently, especially not in combat, since you'll have to wait before fiering again, otherwise your burnout will only increase even more, making your spells even pricier and forcing you to even longer cooldown times, while you aren't even out of mana, but only unable to continue casting magic, because it would kill your mana in a matter of seconds.

I hope this explanation helped you to understand my point and I want to add, that Ars Magica 2 is my favorite mod and I only wanted to help making it even more fantastic.

**Comment by ThatOneTraitor** [comment]
or you know.. you could use the imbument.. which is so strong that the mana regen imbuement seems like a joke in later levels..

**Comment by SneakTrap** [comment]
True, but the point is, that there should be an option to turn burnout off.

**Comment by SneakTrap** [comment]
Will you add an option to turn burnout off?

**Comment by Zsashas** [comment]
I think it's been made clear that the option won't be added, as the mechanic is considered balanced as it is. You should look into armor imbuements.

**Comment by SneakTrap** [comment]
I would still like to hear that from an author, just to be sure.

**Comment by SneakTrap** [comment]
I have decided to try it on my own, but I'm not sure how to. I've tried editing the source code, but I don't know how to get it to work as a mod, that is detected by forge. If anyone could give me advice on this, I'd be very grateful.

**Comment by jjtParadox** [comment]
Join us on IRC here: http://webchat.esper.net/?nick=&channels=ArsMagica

We might not always be around, but stick around (keep the window open) and eventually your question will be answered :smiley:

**Comment by jjtParadox** [comment]
Looks like you hopped on while we all were asleep, so you may need to hang around longer than that :stuck_out_tongue_winking_eye:

**Comment by SneakTrap** [comment]
Ok ;D

**Comment by SneakTrap** [comment]
Woohoo, I did it myself! Anyone interested in a version?

**Comment by SneakTrap** [comment]
I guess I can close this then, right?

**Comment by jjtParadox** [comment]
Link your fork, then probably yeah

**Comment by SneakTrap** [comment]
[AM2 -No Burnout + 6 Summonings.zip](https://github.com/Mithion/ArsMagica2/files/511492/AM2.-No.Burnout.6.Summonings.zip)

**Comment by ZidoGit** [comment]
It's been awhile since you posted this, but I gotta say thanks, i were looking for this!

**Comment by Vergeluria** [comment]
> [AM2 -No Burnout + 6 Summonings.zip](https://github.com/Mithion/ArsMagica2/files/511492/AM2.-No.Burnout.6.Summonings.zip)

8 Years later and this mod version still helping people, thanks for your work. I can finally spam Blink as i used to in 1.6.4, don't know if you will ever see this, but still, thank you very much.
