### ISSUE TITLE
Spell: Projectile Dig

### ISSUE THREAD

**Issue by fallatus** [Mithion/ArsMagica2#345]
Hello,

when I cast the Spell Dig (as Projectile) its not working.
(Tryed both casting modes and spammed the manabar empty!)
I tryed it with Operator permission, this changed nothing at all.
Skill dig is set to true in SkillConf.cfg.

Using 1.6.4 and Ars Magica 2 1.1.1c, mpcp+

**Comment by blahthebiste** [comment]
I ran into this same issue today, it SHOULD be a valid spell combination (in fact that is what I was trying to do) but it cannot mine anything, at a distance or at point blank. It doesn't seem correct that having two shapes should cancel out the effect in such a simple spell

**Comment by Acar77** [comment]
I am having a similar problem but it is related to all projectile spells. after a certain point, the spell will activate but will not travel any distance. i think it may be related to the target non-solid skill as the bug happened after i received it on both attempts to reset the mod but it is not included in the spell.

**Comment by Acar77** [comment]
did some testing and closing out minecraft resets this bug so sorry for bothering you

**Comment by Th3l0stSpart4n** [comment]
I believe this is actually related to a vanilla bug in minecraft that we call ghosting. Basically the server unsyncs the player, this can happen anytime after teleporting into a unloaded chunk and is fixed by death or relog. In vanilla minecraft this can cause a lack of correct particles and sound events to not activate along with complete invisibility including armor, so I'm sure it breaks some part of projectile spells.
